---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# prez

Here I store my presentations in conferences as PDF.

- [2023-11 - You may have already written a package and not even know it](2023-11-17_you_may_have_already_written_a_package_and_not_even_know_it.pdf)

- [2023-06 - {golem} and {fusen}: The winning combo for building robust, easy-to-manage shiny applications](2023-06-22_RR2023_golem-fusen.pdf)

- [2022-11 - Gestion de GitLab automatisée avec {gitlabr} - Meetup R Nantes](2022-11-21_gestion_de_gitlab_automatisee_avec_gitlabr.pdf)

- [2021-07 - {fusen}: Créer un package R à partir de simples fichiers Rmarkdown - Rencontres R Paris](2021-07-12-creer-un-package-depuis-rmd-avec-fusen_RR2021.pdf)

- [2021-07 - Use {fusen} to write or upgrade a package - UseR 2021](https://github.com/statnmap/prez/blob/master/2021-07-use-fusen-to-write-or-upgrade-a-package.pdf)
  - Youtube video is available for UseR attendees there, starting at 22'40: https://www.youtube.com/watch?v=NjM7sG1Lpc4
  -   Related package presented : [{fusen}](https://github.com/thinkr-open/fusen)
        
- [2021-05 - How to build a package with the Rmd first method? - Hebrew R User Group Lille](https://github.com/statnmap/prez/blob/master/2021-05-how-to-build-package-rmd-first-fusen.pdf)
    -   Package build during presentation : [{squirrels.fusen}](https://github.com/statnmap/squirrels.fusen)
    -   Related package presented : [{fusen}](https://github.com/thinkr-open/fusen)
        
- [2021-04 - How to build a package with the Rmd first method? - Meetup R Lille](https://github.com/statnmap/prez/blob/master/2021-04-how-to-build-package-rmd-first-fusen.pdf)
    -   Package build during presentation :
        [{squirrels.fusen}](https://github.com/statnmap/squirrels.fusen)
    -   List of questions and answers on HackMd : https://hackmd.io/2WEGjlnsTNa1-6k_ztAMZA?view
    -   Watch video on Youtube : https://www.youtube.com/watch?v=febuOcS70t4
    -   Related package presented : [{fusen}](https://github.com/thinkr-open/fusen)

- [2020-10 - Development workflow at ThinkR: PROPRE, DataOps and DevOps workflows - ecoinfoFAIR2020](https://github.com/statnmap/prez/blob/master/2020-10-ThinkR-development-workflow.pdf)

- [2020-02 - Transforming scattered analyses into a documented, reproducible and shareable workflow - FOSDEM Brussels](https://github.com/statnmap/prez/blob/master/2020-02_FOSDEM_Rochette_prez.pdf)
  + Watch video at FOSDEM 2020: https://video.fosdem.org/2020/AW1.126/open_research_shareable_workflow.mp4
  + See related blog post (FR) : https://thinkr.fr/transformer-plusieurs-scripts-eparpilles-en-beau-package-r/

- [2019-07 - The "Rmd first" method: when projects start with documentation - useR Toulouse](https://github.com/statnmap/prez/blob/master/2019-07_useR_Toulouse.pdf)
  + See this blog post: <https://rtask.thinkr.fr/rmd-first-when-development-starts-with-documentation>
  + Watch video on Youtube: https://youtu.be/cB1BCxFbhtk
  
- [2019-02 - Everything but maps with spatial tools - SatRday Paris (EN)](https://github.com/statnmap/prez/blob/master/2019-02-22_SatRdays_Paris.pdf)

  + Watch video on Youtube: https://youtu.be/Gwb1aeD_sVs
  + Get the (not totally reproducible) [Rmd of the presentation](https://github.com/statnmap/prez/blob/master/2019-02-22_SatRdays_Paris.Rmd)
 
- [2018-07 - Les SIG et la cartographie avec R - Rencontres R (FR)](https://github.com/statnmap/prez/blob/master/2018-07-06_RR2018_Statnmap.pdf)
  + See this blog post (FR & EN) for this presentation: <https://statnmap.com/2018-07-14-introduction-to-mapping-with-sf-and-co/>
  
